language: cpp
compiler: clang
env:
  global:
    - secure: "sI8EY9vmX7JcimIBpfe1H7yQanNr0Zp8Y2Tv7Io7otVor48emWUhTkFB0hv/U8K+izCgviJX9w9D1FKiQVr2wGOdQRXV/YALjF+Sxc8ECi04THgopkxffTM4Nzvq1xVQJyqbfLjVJN1i4wzS+tKZaTODt/wtfN8a4wlfH7iVl5c="
cache:
  apt: true
  directories:
    - Qt
before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt541
  - sudo apt-add-repository --yes ppa:libreoffice/libreoffice-4-2
  - sudo apt-get update -qq
install:
  - sudo pip install PyYAML cpp-coveralls cpplint
  - sudo apt-get install qt54base qt54tools qt54declarative doxygen graphviz mesa-utils xvfb
before_script:
  - export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - glxinfo
  - /opt/qt54/bin/qmake -unix SickleTest.pro
script:
  - make lint
  - make
after_success:
  - chmod ugo+x scripts/build-docs.sh
  - ./scripts/build-docs.sh
  - coveralls --exclude-pattern moc_
deploy:
  provider: releases
  api-key:
    secure: "Tq7NV2xn6bYSc/y9seTNlNuC/ceuA6SbWZ+EWLSF1jFB23nH+FnouZvZdWWZTKtH1kjtIOpVj+5TwLDxzFOL2jYGGhFifuztxD8c4n7K2br3NBF4zSXRWFvGXKvEoi0cJLwuWO22WCs+ESrLKWNzQVxRTUABbfRYd1089muqaf0="
  file: "release/GameEditor.exe"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
notifications:
  slack: sup3asc2:DzHmU0Cfxw0UoWVs5r0Ph7Uf
